### ISSUE TITLE
Support for Node 6.x?

### ISSUE THREAD

**Issue by portokallidis** [cognitom/wdio-phantomjs-service#7]
Hi I installed your example(https://github.com/cognitom/webdriverio-examples.git) for only phantomjs setup.
I am on node v6.9.4
And got this:
```
$ wdio test/wdio.conf.js
A service failed in the 'onPrepare' hook
Error: Exit code: 127
    at ChildProcess.<anonymous> (/home/nporto/wdio-test/node_modules/phantomjs-prebuilt/lib/phantomjs.js:117:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
```

i npm installed on a fresh ubuntu 16.04 with nodejs v6.9.4 and npm 3.10.10

**Comment by portokallidis** [comment]
I installed selenium standalone and then got another error,
It couldnt find the binary path so i did that:
``` 
exports.config = {
  capabilities: [
    { 
      'browserName': 'phantomjs',
      'phantomjs.binary.path': '/home/nporto/wdio-test/node_modules/phantomjs-prebuilt/bin/phantomjs'
    }
```

And then i stopped the selenium standalone server and continues to work.

Can this be done without installing java and selenium?

**Comment by cognitom** [comment]
Hi @portokallidis, we have tests on Node 6, too. It should work.
https://github.com/cognitom/wdio-phantomjs-service/blob/master/.travis.yml

**Comment by pscheit** [comment]
apt get install libfontconfig
fixes this for me
